### ISSUE TITLE
Isn't the example going to throw ClassCastException?

### ISSUE THREAD

**Issue by dalewking** [Workable/java-error-handler#2]
The readme example has this declaration:

```
  // Bind HTTP 404 status to 404
  .bind(404, errorCode -> throwable -> {
      return ((HttpException) throwable).code() == 404;
  })

  // Bind HTTP 500 status to 500
  .bind(500, errorCode -> throwable -> {
      return ((HttpException) throwable).code() == 500;
  })
```

If the error given to handle method is not an HttpException won't you get a ClassCastException?

**Comment by pavlospt** [comment]
Yes, we actually haven't updated the example. We are going to fix it :) Thank you!

**Comment by pavlospt** [comment]
You can see a better example of this handling here: https://github.com/Workable/java-error-handler/blob/master/errorhandler-matchers/retrofit-rx-matcher/src/main/java/com/workable/errorhandler/matchers/retrofit/RetrofitMatcherFactory.java

**Comment by pavlospt** [comment]
Fixed on master!
