### ISSUE TITLE
Would be nice to have a shorthand bind call for mapping directly from exception type to error code

### ISSUE THREAD

**Issue by dalewking** [Workable/java-error-handler#3]
A signature like this:

```
public <T> ErrorHandler bind(T errorCode, Class<Throwable> types...)
```

That basically says any if the exception is any of the given types map it to the given error code.

**Comment by dalewking** [comment]
It's basically shorthand so that this from the example:

```
.bind("offline", errorCode -> throwable -> {
    return throwable instanceof UnknownHostException || throwable instanceof ConnectException;
})
```

could instead be specified as:

```
.bind("offline", UnknownHostException.class, ConnectException.class)
```

**Comment by pavlospt** [comment]
The example's use case, uses a MatcherFactory that in turn generates a Matcher which checks for both the classes. This can easily be done if you build your own custom MatcherFactory :) Let us know if you need any assistance on this.

**Comment by dalewking** [comment]
I know it is not difficult to write the matcher as is shown in the example, but it is verbose and this is a common enough case to justify providing in a method of ErrorHandler

**Comment by pavlospt** [comment]
We will consider adding it later on then, if you think it is a common case :)
