### ISSUE TITLE
Need a way to define a common action based on the type of error code

### ISSUE THREAD

**Issue by dalewking** [Workable/java-error-handler#4]
Say I have a bunch of bind calls that map exceptions to value of MyEnum class as in:

```
.bind(MyEnum.Foo, errorCode -> throwable -> throwable instanceof SomeException)
.bind(MyEnum.Bar, errorCode -> throwable -> throwable instanceof SomeOtherException)
```

I would like to define an action to take for any value of MyEnum type as in:

```
.on(MyEnum.class, (enumValue, throwable, errorHandler) -> doSomething())
```

**Comment by pavlospt** [comment]
Similarly to your previous question you can use another MatcherFactory and create the desired behavior since you want to do it for every value of your Enum class. Check the example below: 

```
ErrorHandler
                .createIsolated()
                .bindClass(DBError.class, errorCode -> throwable -> throwable instanceof DBErrorException)
                .on(DBError.READ_ONLY, (throwable, errorHandler) -> {
                    actionDelegateMock.action1();
                    errorHandler.skipAlways();
                })
                .on(DBError.DEADLOCK, (throwable, errorHandler) -> {
                    actionDelegateMock.action2();
                    errorHandler.skipAlways();
                })
                .on(DBError.FATAL, (throwable, errorHandler) -> {
                    actionDelegateMock.action3();
                    errorHandler.skipAlways();
                })
                .run(() -> {
                    throw new DBErrorException("read-only");
                });
```

**Comment by dalewking** [comment]
No, that is the exact opposite of what I described. You show a _different_ action for each enum value. I want the _same_ action for all enum values. In my case the enum values contain information about how to process it (e.g. the message to show)

**Comment by th3hunt** [comment]
Hello @dalewking, yes of course you can:

Here you go:

``` java
ErrorHandler
.create()
.bind(MyEnum.class, errorCode -> throwable -> throwable instanceof SomeException || throwable instanceof SomeOtherException)
.on(MyEnum.class, (throwable, errorHandler) -> doSomething(throwable));
```

**Comment by th3hunt** [comment]
@dalewking However, I don't see why you'd want to do that in the first place. Enumerations are nice so that we can map long and ugly exception names to something friendlier and easier to remember or reason about.

`ErrorHandler` for example lets you easily map 
- `ConnectException` containing "offline" somewhere in it's message to `Network.OFFLINE` 
- `ConnectException` containing "host not found" somewhere in it's message to `Network.DNS_ERROR` // random strings here didn't look em up :)
- `SocketTimeoutException` to `Network.TIMEOUT`

And define those mapping on `ErrorHandler.defaultErrorHandler()` so that everywhere else you just type things like `.on(Network.TIMEOUT, () -> showTryAgainDialog())` which is easy to read and understand.

However, if you need to have a single handler for all occurrences of a single exception you can just use https://github.com/Workable/java-error-handler/blob/master/errorhandler/src/main/java/com/workable/errorhandler/ErrorHandler.java#L138 without having to `bind` anything to an enum.

``` java
ErrorHandler
.create()
.on(SomeException.class, (throwable, errorHandler) -> doSomething(throwable));
```

or if you need a common handler for more than 1 type of exceptions:

``` java
ErrorHandler
  .create()
  .on(
      (throwable) -> throwable instanceof SomeException || throwable instanceof SomeOtherException,
      (throwable, handler) -> doSomething()
  );
```

**Comment by dalewking** [comment]
> Enumerations are nice so that we can map long and ugly exception names to something friendlier and easier to remember or reason about.

The problem is that is all you see them as. In our case the enum (which already exists in our system) contains additional information that is vital for processing the error. For example, In our system we have a user visible error log that the user can see. In that log, errors are assigned a specific error code to be shown to the user. Two pieces of information contained in the enum are whether this particular error is one that gets logged to the user visible log and what error code is displayed for the error. There are additional things determined from the enum using switch statements like what error message to show to the user in a dialog (I cannot use a switch statement on a throwable).

None of your proposals give me access to the actual enum value in the Action which is the most important piece of information for me. In order to use your proposal I would need to convert the throwable to the enum value with a big if-else chain with a bunch of instanceof calls, but wasn't that the whole point of the bind calls.

All I am really asking for is something of the form:

```
.on(MyEnum.class, (enumValue, throwable, errorHandler) -> doSomething(enumValue, throwable));
```

**Comment by th3hunt** [comment]
@dalewking How does an `enumValue` derive from a `throwable` ? I mean there has to be an association somewhere.

Wouldn't something like this work for you?

```
.on(MyEnum.class, (throwable, errorHandler) -> doSomething(enumValueFromError(throwable));
```

**Comment by dalewking** [comment]
Right now the mapping is done with huge try catch clauses around the code that catch all the exception types that then wrap that into another exception type that includes the enum value as in:

```
try
{
     // code that throws exceptions
}
catch(SomeException e)
{
    throw new WrappedError(MyEnum.Foo, e);
}
catch(SomeOtherException e)
{
    throw new WrappedError(MyEnum.Bar, e);
}
// and a bunch more
```

 That is what I want to get rid of and replace with your error handler so that I can separate the error handling from the code that throws the exceptions. Right now the code is dwarfed by all the catch clauses.

If the enumValueFromError function existed (and I assure you it does not), think about what that would look like. It would have to be something like this:

```
if(throwable instanceof SomeException) return MyEnum.Foo;
else if(throwable instanceof SomeOtherException) return MyEnum.Bar;
// And so on
```

Gee, that looks an awful lot like what the bind code in the error handler is doing. Wouldn't it be awfully silly to duplicate that logic? All I am asking is that the result of the bind call doesn't get discarded and can be used in the action of the on call.

**Comment by dalewking** [comment]
> Hello @dalewking, yes of course you can:
> 
> Here you go:
> 
> ErrorHandler
> .create()
> .bind(MyEnum.class, errorCode -> throwable -> throwable instanceof SomeException || throwable instanceof SomeOtherException)
> .on(MyEnum.class, (throwable, errorHandler) -> doSomething(throwable));

And the on method you show here does not exist.

**Comment by dalewking** [comment]
Why was this closed?
