### ISSUE TITLE
Add possibility to specify parentErrorHandler

### ISSUE THREAD

**Issue by androidmitry** [Workable/java-error-handler#7]
Hello, everyone, thanks you for this useful framework. I faced the problem when I need some parentErrorHandler, but I can't use singleton object. I think my issue can be simply solved just by adding factory method.
`public static ErrorHandler create(ErrorHandler parentErrorHandler) {
        return new ErrorHandler(parentErrorHandler);
    }`

What do you think about it?

**Comment by th3hunt** [comment]
Hello @androidmitry.

Sorry for my late response. That's good to hear :)

Actually, `ErrorHandler` is built with that mechanism but we were reluctant in adding to the public API. Can you give us a few days to decide on this? 

@pavlospt @charbgr what do you think?

**Comment by charbgr** [comment]
@th3hunt I think we should include this feature and we already discussed this internally.

One problem is for `ErrorHandler` instance with existing parent `ErrorHandler` specified. We should restrict the passed `ErrorHandler` instance to not have a parent `ErrorHandler`.

For example, what will happen if the passed `ErrorHandler` has a `parentErrorHandler` ?
Should we allow this chain?
```java
ErrorHandler.create(ErrorHandler.create(ErrorHandler.create(...)))
```

Chains of `ErrorHandler`s will make the API confusing and I don't know how `skipDefaults` or `always` actions will perform.

**Comment by androidmitry** [comment]
Hello @th3hunt , @charbgr 

I managed to solve my issue by wrapping ErrorHandlers.

```
ErrorHandler.createIsolated().on(IOException.class, new Action() {
        @Override
        public void execute(Throwable throwable, ErrorHandler errorHandler) {
            // handle particular error
        }
    })
    .otherwise(new Action() {
        @Override
        public void execute(Throwable throwable, ErrorHandler errorHandler) {
            // Use any ErrorHandler previously configured as parent or default
            ErrorHandler.defaultErrorHandler().handle(throwable);
        }
    })
    .handle(error);
```

Reopen issue if you still need such feature. Thank you for your help.
