### ISSUE TITLE
How can we use in a complex project

### ISSUE THREAD

**Issue by birender-s** [Workable/java-error-handler#8]
Hi please advise how we can implement in project where erros can happen at multiple places like service call (Retrofit lib used in background thread, UI vaidation error in fragment...). Something like this project https://github.com/googlesamples/android-architecture/tree/dev-todo-mvvm-live

**Comment by pavlospt** [comment]
Hey @birender-s , could you please point us to a class that handles errors on your mentioned example? We could provide an example for that case :)

**Comment by birender-s** [comment]
Hi @pavlospt , firstly thanks for prompt response.
The project i've shared is a reference project from Google team which uses MVVM based Android Architecture Components (recent classes introduced by Google) and it currently doesn't have a error handling class. But the errors can happen at multiple places, e.g. :
1) TasksRemoteDataSource which is responsible to invoke REST APIs (currently dummy responses) using in background thread. Here, Retrofit lib will be used to API calls and Retrofit will be initialized at central place something like this :

        OkHttpClient.Builder httpClient = new OkHttpClient.Builder();
        httpClient.readTimeout(NetworkConstants.API_READ_TIMEOUT, TimeUnit.SECONDS);
        httpClient.connectTimeout(NetworkConstants.API_CONNECT_TIMEOUT, TimeUnit.SECONDS);
        // add cache path
        httpClient.cache(cache);

        httpClient.addInterceptor(logging);

        return new Retrofit.Builder()
                .baseUrl(baseUrl)
                .addConverterFactory(JacksonConverterFactory.create(mapper))
                .client(httpClient.build()).
                        build().create(apiServices);
There could be multiple service calls invoked in multiple classes.
So SocketTimeoutException, 404 errors etc needs to be handled at central place and we would like to display "offline" kind of errors.
2) TasksViewModel which could do some local validations, so based on those errors, we would like to display error message in SnackBar 
In both the cases, we don't have Activity/Fragment handle to display Snackbar directly. Moreover, in 1st case, since it's background thread (not main). How can we leverage defaultErrorHandler() and handle throwable error so the implementation is done at one place and not scattered across (the problem that your library addresses). 
In your error-handler-demo project, initiateAPICall() and handleWithErrorHandler(ErrorHandler.create() within) are defined within activity and hence it's possible. But how can we achieve same in above project/design. I think if this works, we can approach google team to consider your library for inclusion into reference project so it helps the whole Android community !

**Comment by pavlospt** [comment]
@birender-s Regarding 1) I can explain you what we are doing and see if it fits your case: 
We are using RxJava in our projects, so we are able to access the `Throwable` in our `Observers`/`Subscribers` and handle it accordingly.

Provided that you have declared and instantiated a `default` ErrorHandler with the `bind`s that you need in your project, error handling becomes one line :) `ErrorHandler.create().handle(throwable)` in Java and in Kotlin you could also write a simple extension function to make that even smaller: 

```kotlin
fun Throwable.handle(func: ErrorHandler.() -> Unit = {}) {
  val errorHandler = ErrorHandler.create()
  func(errorHandler)
  errorHandler.handle(this)
}
```

Now it becomes, as simple as, `throwable.handle()`!

We use GreenRobot's EventBus to propagate events from the `default` ErrorHandler in our BaseActivity and accordingly handle them, in case there is no local handling and prevention of the error propagation to the `default` ErrorHandler, which is expressed like the following:

```java
ErrorHandler.create().on(404, (throwable, errorHandler) -> {
      //your error handling code here
      errorHandler.skipDefaults(); //this line prevents default ErrorHandler from handling the 404 error
});
```

2) In that case, ViewModel could use a `LiveData` and propagate the error, hence the `Throwable` to the `Observer` which can leverage ErrorHandler to display the appropriate feedback for each of your errors.

**Comment by pavlospt** [comment]
@birender-s should we close the issue? Is everything clear from the explanation above? :)

**Comment by birender-s** [comment]
hi @pavlospt , firstly sorry for the delayed response. Thanks much for the explanation, i think the suggested approach should work. ii wanted to try the approach before responding and it's not done yet due to other priority items.

**Comment by birender-s** [comment]
Closing the issue for now and will get back if I need further inputs. Thanks once again !
